// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VuePack
{
    internal sealed partial class Vsix
    {
        public const string Id = "8a31a789-50bf-4e95-b4f9-b50877f2b523";
        public const string Name = "Vue.js Pack 2019";
        public const string Description = @"Contains HTML Intellisense and code snippets for the Vue.js JavaScript library";
        public const string Language = "en-US";
        public const string Version = "1.2";
        public const string Author = "Mads Kristensen";
        public const string Tags = "vue.js, snippets, javascript";
    }
}
